### ISSUE TITLE
RM2+ scan frequency support

### ISSUE THREAD

**Issue by nick7zmail** [tasict/broadlink-device-php#1]
Hello.
Can you add scan frequency support for RM2+ devices?

To scan the RF command, rm2+ must determine the frequency first. 
For example in this project http://rm-bridge.fun2code.de/ there is a separate button for the scan frequency with a certain type of device.

// Quote
```
            <div ng-show="device.type == '10026'">
                If learning RF codes, <b>RM Pro+</b> devices must do a frequency scan before learning a code.
                <br> Press the <i><b>Frequency Scan</b></i> and then long press the button on your remote for approx. 5 seconds.
                <br> During this process the LED should light up and stay lit even after the scan is complete.
                <br>
                <p>
                    <button class="button" ng-click="freqScan()">Frequency Scan</button>
                    <!-- <button class="button" ng-click="freqScanCancel()">Cancel Scan</button> -->
                </p>
            </div>
```
//Quote

**Comment by tasict** [comment]
RF support is already built in.
I test RF remote device with my rm pro and it has no problem to control last day.
Could you tell me what trigger scan frequency is need?

**Comment by nick7zmail** [comment]
It is only RM2 PLUS feauture. Before learning, device must scan frequency. I dont know how else to explain it, but device is not learning rf commands.

**Comment by kas5858** [comment]
I have a RM2+ Kaidij devices and digital remote control switch RF I taught "D" button once, the button "C, B" c different manipulations, button "A" is not obuchaetsya.

**Comment by nick7zmail** [comment]
Sorry, everything works.
