### ISSUE TITLE
Noob problem

### ISSUE THREAD

**Issue by ksperr** [tasict/broadlink-device-php#2]
When i try to run "discover.php" on on my localhost xampp it only shows this:
devtype();
	$obj['name'] = $device->name();
	$obj['mac'] = $device->mac();
	$obj['host'] = $device->host();
	$obj['model'] = $device->model();
	if($obj['model'] == "RM2"){
		$device->Auth();
		$temperature = $device->Check_temperature();
		$obj['temperature'] = $temperature;
	}
	else if($obj['model'] == "A1"){
		$device->Auth();
		$data = $device->Check_sensors();
		$obj = array_merge($obj, $data);
	}
	array_push($result, $obj);
}
echo json_encode($result);

I configured php.ini as development. What i'm doing wrong?

**Comment by tasict** [comment]
This is not project issue. Please make sure your php environment work well.

**Comment by antotor** [comment]
change <? tag to <?php
